config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  get '/signup', to: 'users#new'
  # ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'

  # Google OAuth
  #get '/auth/:provider/callback', to: 'sessions#create'
  #post '/auth/:provider/callback', to: 'sessions#create'
  #get '/auth/failure', to: 'sessions#failure'
  
   # google
    #get '/auth/:provider/callback', to: 'sessions#create'
   post '/auth/:provider/callback', to: 'sessions#create'
   get 'auth/signout' => 'sessions#destroy'
   get 'auth/:provider/callback', to: 'sessions#create'
   get 'auth/failure', to: redirect('/')
   get 'log_out', to: 'sessions#destroy', as: 'log_out'

  


  resources :users do
    member do
      # ユーザー基本情報
      get 'edit_basic_info'
      patch 'update_basic_info'

      # マイページ関連
      get 'work_out'
      patch 'work_out'
      get 'workout_menu'
      
      # トレーニング部位選択ページ
      get 'muscle_parts_page'
      patch 'muscle_parts_page'

      # 部位別トレーニングページ
      # 以下のトレーニング関連ルートをTrainingControllerに変更
      get 'training_arms_modal', to: 'training#training_arms_modal'
      patch 'update_arms_modal', to: 'training#update_arms_modal'
      get 'training_abs_modal', to: 'training#training_abs_modal'
      patch 'update_abs_modal', to: 'training#update_abs_modal'
      get 'training_back_modal', to: 'training#training_back_modal'
      patch 'update_back_modal', to: 'training#update_back_modal'
      get 'training_chest_modal', to: 'training#training_chest_modal'
      patch 'update_chest_modal', to: 'training#update_chest_modal'
      get 'training_shoulder_modal', to: 'training#training_shoulder_modal'
      patch 'update_shoulder_modal', to: 'training#update_shoulder_modal'
      get 'training_thighs_modal', to: 'training#training_thighs_modal'
      patch 'update_thighs_modal', to: 'training#update_thighs_modal'

      # トレーニング一覧ページもTrainingControllerに変更
      get 'training_abs', to: 'training#training_abs'
      get 'training_chest', to: 'training#training_chest'
      get 'training_arms', to: 'training#training_arms'
      get 'training_thighs', to: 'training#training_thighs'
      get 'training_shoulder', to: 'training#training_shoulder'
      get 'training_back', to: 'training#training_back'
      
    end
    resources :training_histories
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :department, length: { in: 2..30 }, allow_blank: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返します。
  class << self
    def find_or_create_from_auth_hash(auth_hash)
      user_params = user_params_from_auth_hash(auth_hash)
      find_or_create_by(email: user_params[:email]) do |user|
        user.update(user_params)
      end
    end
  
    def user_params_from_auth_hash(auth_hash)
      {
        name: auth_hash.info.name,
        email: auth_hash.info.email,
        password: auth_hash.info.email,
        password_confirmation: auth_hash.info.email,
        
        # image: auth_hash.info.image,
      }
    end
  end
  
  

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :update]
  
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @first_day = params[:date].nil? ? 
      Date.current.beginning_of_month : params[:date].to_date.beginning_of_month
    @days_of_the_week = %w[日 月 火 水 木 金 土]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    target_part = params[:user][:target_part]
    menu_content = params[:user][:menu_content]
  
    if @user.update("#{target_part}": menu_content)
      flash[:success] = "メニューを更新しました"
      redirect_to workout_menu_user_path(@user)
    else
      flash[:danger] = "更新に失敗しました"
      redirect_to workout_menu_user_path(@user)
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user == current_user
      # ユーザーに関連する全てのデータを削除
      @user.destroy
      # セッションを削除してログアウト
      log_out
      flash[:success] = "アカウントを削除しました"
      redirect_to root_url
    else
      flash[:danger] = "削除権限がありません"
      redirect_to users_url
    end
  end

  def edit_basic_info
    @user = User.find(params[:id])
  end

  def update_basic_info
  end
  
  def muscle_parts_page
    @user = User.find(params[:id])
    date = params[:date].to_date
  end  
  
  def training_abs
    @users = User.all
  end
  
  def update_abs_modal
    @user = User.find(params[:id])
    puts params[:user][:abs]
    if @user.update(user_params)
      flash[:success] = "トレーニングメニューを登録しました。"
      redirect_to user_url(@user)
    else
      flash[:error] = "トレーニングメニューを登録に失敗しました。"
      render :edit
    end
  end

  def training_abs_modal
    @user = User.find(params[:id])
  end

  def training_arms
    @users = User.all
  end

  def training_arms_modal
    @user = User.find(params[:id])
  end  

  def update_arms_modal 
    @user = User.find(params[:id])
    puts params[:user][:arms]
    if @user.update(user_params)
      flash[:success] = "トレーニングメニューを登録しました。"
      redirect_to user_url(@user)
    else
      flash[:error] = "トレーニングメニューを登録に失敗しました。"
      render :edit
    end
  end
 
  def training_back
    @users = User.all
  end 

  def training_back_modal
    @user = User.find(params[:id])
  end 

  def update_back_modal
    @user = User.find(params[:id])
    puts params[:user][:back]
    if @user.update(user_params)
      flash[:success] = "トレーニングメニューを登録しました。"
      redirect_to user_url(@user)
    else
      flash[:error] = "トレーニングメニューを登録に失敗しました。"
      render :edit
    end
  end

  def training_chest
    @users = User.all
  end 

  def training_chest_modal
    @user = User.find(params[:id])
  end

  def update_chest_modal
    @user = User.find(params[:id])
    puts params[:user][:chest]
    if @user.update(user_params)
      flash[:success] = "トレーニングメニューを登録しました。"
      redirect_to user_url(@user)
    else
      flash[:error] = "トレーニングメニューを登録に失敗しました。"
      render :edit
    end
  end
  
  def training_shoulder
    @users = User.all
  end 

  def training_shoulder_modal
    @user = User.find(params[:id])
  end

  def update_shoulder_modal
    @user = User.find(params[:id])
    puts params[:user][:shoulder]
    if @user.update(user_params)
      flash[:success] = "トレーニングメニューを登録しました。"
      redirect_to user_url(@user)
    else
      flash[:error] = "トレーニングメニューを登録に失敗しました。"
      render :edit
    end
  end

  def training_thighs
    @users = User.all
  end 

  def training_thighs_modal
    @user = User.find(params[:id])
    respond_to do |format|
      format.html
      format.js   # JavaScript形式のレスポンスを追加
    end
  end

  def update_thighs_modal
    @user = User.find(params[:id])
    puts params[:user][:thighs]
    if @user.update(user_params)
      flash[:success] = "トレーニングメニューを登録しました。"
      redirect_to user_url(@user)
    else
      flash[:error] = "トレーニングメニューを登録に失敗しました。"
      render :edit
    end
  end

  def work_out
    @user = User.find(params[:id])
    @date = params[:date].to_date
  end


  def workout_menu
    @user = User.find(params[:id])
    @training_history = TrainingHistory.new  # 新規記録用のインスタンスを作成
    @training_histories = TrainingHistory.where(user_id: @user.id)  # 履歴一覧用
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :arms, :abs, :chest, :back, :shoulder, :thighs)
  end
    
  # beforeフィルター

  # paramsハッシュからユーザーを取得します。
  def set_user
    @user = User.find(params[:id])
  end

  # ログイン済みのユーザーか確認します。
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "ログインしてください。"
      redirect_to login_url
    end
  end

  # アクセスしたユーザーが現在ログインしているユーザーか確認します。
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>


<%= turbo_frame_tag 'modal' do %>
  <div class="modal-dialog modal-lg modal-dialog-center" data-controller="edit-basic-info">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-action="edit-basic-info#close" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h1 class="modal-title">基本情報編集</h1>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: false, method: :patch, data: { action: "submit->edit-basic-info#submit" }) do |f| %> 
              <%= render 'shared/error_messages', object: @user %>
  
              <%= f.label :name, class: "label-#{yield(:class_text)}" %>
              <p><%= @user.name %></p>

  
              <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
              <%= f.time_field :basic_time, class: "form-control" %>
  
              <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
              <%= f.time_field :work_time, class: "form-control" %>
  
              <div class="center">
                <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
                <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-action="edit-basic-info#close">
                  キャンセル
                </button>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= j(render 'edit_basic_info', user: @user) %>");
$("#edit-basic-info").modal("show");

app/views/users/index.html.erb
<% provide(:title, "勤怠ログ") %>

<div class="user-list-container">
  <div class="container">
    <div class="content-wrapper">
      <h1 class="page-title">マイページ</h1>

      <div class="table-responsive">
        <table class="table table-hover table-custom">
          <thead>
            <tr>
              <th>ユーザー名</th>
              <th class="text-center">操作</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td class="user-name">
                  <%= link_to user.name, user_path(user), class: "user-link" %>
                </td>
                <td class="text-center">
                  <% if current_user == user %>
                    <%= link_to '基本情報編集', 
                        workout_menu_user_path(user),
                        data: { turbo_frame: 'modal' }, 
                        class: "btn btn-edit text-white" %>
                    <%= button_to "削除", 
                        user_path(user), 
                        method: :delete,
                        data: { confirm: "本当にアカウントを削除してよろしいですか？" },
                        class: "btn btn-delete text-white",
                        form: { style: 'display: inline-block;' } %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<%= turbo_frame_tag "modal" %>

# app/assets/stylesheets/users.scss
.user-list-container {
  background-color: #f5f7fa;
  min-height: 100vh;
  padding: 2rem 0;
}

.content-wrapper {
  background-color: white;
  border-radius: 10px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  padding: 2rem;
}

.page-title {
  color: #2c3e50;
  font-size: 1.8rem;
  font-weight: 600;
  margin-bottom: 2rem;
  text-align: center;
}

.table-custom {
  margin-top: 1rem;

  thead th {
    background-color: #f8fafd;
    color: #2c3e50;
    border-bottom: 2px solid #e9ecef;
    padding: 1rem;
  }

  tbody td {
    padding: 1rem;
    vertical-align: middle;
  }
}

.user-name {
  font-size: 1.1rem;
  color: #2c3e50;

  .user-link {
    color: inherit;
    text-decoration: none;
    
    &:hover {
      color: #3498db;
    }
  }
}

.btn-edit {
  background-color: #2ecc71;
  border-color: #27ae60;
  margin-right: 0.5rem;

  &:hover {
    background-color: #27ae60;
    border-color: #219d53;
  }
}

.btn-delete {
  background-color: #e74c3c;
  border-color: #c0392b;
  color: white;
  margin-left: 0.5rem;

  &:hover {
    background-color: #c0392b;
    border-color: #a93226;
    color: white;
  }
}

form {
  margin: 0;
}

app/views/users/muscle_parts_page.html.erb
<h1>部位選択</h1>
<table class="table table-bordered table-condensed user-table">
 <td><%= link_to "胸", training_chest_user_path(@user), class: "btn btn-primary" %>
 <td><%= link_to "腕", training_arms_user_path(@user), class: "btn btn-primary" %>
 <td><%= link_to "太もも", training_thighs_user_path(@user), class: "btn btn-primary" %>
 <td><%= link_to "肩", training_shoulder_user_path(@user), class: "btn btn-primary" %>
 <td><%= link_to "背中", training_back_user_path(@user), class: "btn btn-primary" %>
 <td><%= link_to "腹筋", training_abs_user_path(@user), class: "btn btn-primary" %>
</table> 

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<style>
.page-container {
  background-color: #f5f7fa;
  min-height: 100vh;
  padding: 2rem 0;
}

.content-wrapper {
  background-color: white;
  border-radius: 10px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  padding: 2rem;
}

.user-name {
  color: #2c3e50;
  font-size: 1.8rem;
  font-weight: 600;
  margin-bottom: 2rem;
}

.month-navigation {
  background-color: #ffffff;
  padding: 1.2rem;
  border-radius: 8px;
  margin-bottom: 2rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05);
}

.month-text {
  color: #2c3e50;
  font-size: 1.5rem;
  font-weight: 500;
  margin: 0 1.5rem;
}

.nav-btn {
  padding: 0.5rem 1.2rem;
  font-size: 1rem;
  font-weight: 500;
  color: #3498db;
  border: 2px solid #3498db;
  border-radius: 6px;
  transition: all 0.3s ease;
}

.nav-btn:hover {
  background-color: #3498db;
  color: white;
}

.table-custom {
  margin-top: 1rem;
}

.table-custom thead th {
  background-color: #f8fafd;
  color: #2c3e50;
  font-weight: 600;
  padding: 1rem;
  border-bottom: 2px solid #e9ecef;
}

.table-custom tbody td {
  padding: 0.8rem;
  vertical-align: middle;
}

.sunday {
  color: #e74c3c;
}

.saturday {
  color: #3498db;
}

.holiday {
  color: #e74c3c;
  background-color: #fdf2f2;
}

.current-day {
  background-color: #f4f9ff;
}

.btn-menu {
  background-color: #3498db;
  color: white;
  border: none;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  transition: all 0.2s ease;
}

.btn-menu:hover {
  background-color: #2980b9;
  color: white;
}
</style>

<div class="page-container">
  <div class="container">
    <div class="content-wrapper">
      <h1 class="user-name text-center"><%= @user.name %></h1>

      <%# Month Navigation %>
      <div class="month-navigation d-flex justify-content-center align-items-center">
        <%= link_to user_path(date: @first_day.prev_month), class: "nav-btn text-decoration-none" do %>
          ＜ 前月
        <% end %>
        <span class="month-text"><%= @first_day.strftime('%Y年%m月') %></span>
        <%= link_to user_path(date: @first_day.next_month), class: "nav-btn text-decoration-none" do %>
          次月 ＞
        <% end %>
      </div>

      <%# Workout Table %>
      <div class="table-responsive">
        <table class="table table-bordered table-hover table-custom">
          <thead>
            <tr>
              <th width="20%">日付</th>
              <th width="20%">曜日</th>
              <th width="30%">トレーニング部位</th>
              <th width="30%">一覧選択/追加</th>
            </tr>
          </thead>
          <tbody>
            <% (@first_day..@first_day.end_of_month).each do |date| %>
              <% 
                css_class = case date.wday
                          when 0
                            'sunday'
                          when 6
                            'saturday'
                          end
                css_class = 'holiday' if HolidayJapan.check(date)
                css_class = "#{css_class} current-day" if date == Date.current
              %>
              <tr class="<%= css_class %>">
                <td><%= date.strftime('%m/%d') %></td>
                <td><%= @days_of_the_week[date.wday] %></td>
                <td>
                  <% if date == Date.current %>
                    <%= link_to work_out_user_path(@user, date: date), 
                        class: "btn btn-menu w-100" do %>
                      メニュー
                    <% end %>
                  <% end %>
                </td>
                <td>
                  <% if date == Date.current %>
                    <%= link_to muscle_parts_page_user_path(@user, date: date),
                        class: "btn btn-menu w-100" do %>
                      一覧表示/追加
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/update_basic_info.turbo_stream.erb
<%= turbo_stream.replace 'flash', partial: 'shared/flash_messages' %>

app/views/users/work_out.html.erb
<% provide(:title, "勤怠ログ") %>
<style>
.user-list-container {
  background-color: #f5f7fa;
  min-height: 100vh;
  padding: 2rem 0;
}
.content-wrapper {
  background-color: white;
  border-radius: 10px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  padding: 2rem;
}
.page-title {
  color: #2c3e50;
  font-size: 1.8rem;
  font-weight: 600;
  margin-bottom: 2rem;
  text-align: center;
}
.table-custom {
  margin-top: 1rem;
}
.table-custom thead th {
  background-color: #f8fafd;
  color: #2c3e50;
  border-bottom: 2px solid #e9ecef;
  padding: 1rem;
}
.table-custom tbody td {
  padding: 1rem;
  vertical-align: middle;
}
.user-name {
  font-size: 1.1rem;
  color: #2c3e50;
}
.btn-edit {
  background-color: #2ecc71;
  border-color: #27ae60;
  margin-right: 0.5rem;
}
.btn-edit:hover {
  background-color: #27ae60;
  border-color: #219d53;
}
.btn-delete {
  background-color: #e74c3c;
  border-color: #c0392b;
  color: white;
  margin-left: 0.5rem;
}
.btn-delete:hover {
  background-color: #c0392b;
  border-color: #a93226;
  color: white;
}
/* インラインフォームのスタイル調整 */
form {
  margin: 0;
}
</style>
<div class="user-list-container">
  <div class="container">
    <div class="content-wrapper">
      <h1 class="page-title">マイページ</h1>
      <div class="table-responsive">
        <table class="table table-hover table-custom">
          <thead>
            <tr>
              <th>ユーザー名</th>
              <th class="text-center">操作</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @user.name %>
              </td>
              <td class="text-center">
                <% if current_user == @user %>
                  <%= link_to '基本情報編集', 
                      workout_menu_user_path(@user),
                      data: { turbo_frame: 'modal' }, 
                      class: "btn btn-edit text-white" %>
                  <%= button_to "削除", 
                      user_path(@user), 
                      method: :delete,
                      data: { confirm: "本当にアカウントを削除してよろしいですか？" },
                      class: "btn btn-delete text-white",
                      form: { style: 'display: inline-block;' } %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/workout_menu.html.erb
<%# app/views/users/workout_menu.html.erb %>
<% provide(:title, "トレーニングメニュー") %>

<style>
  .workout-container {
    background-color: #f5f7fa;
    min-height: 100vh;
    padding: 2rem 0;
  }

  .content-wrapper {
    background-color: white;
    border-radius: 10px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    padding: 2rem;
    margin: 0 auto;
    max-width: 1200px;
  }

  .page-title {
    color: #2c3e50;
    font-size: 1.8rem;
    font-weight: 600;
    margin-bottom: 2rem;
    text-align: center;
  }

  .user-info {
    margin-bottom: 2rem;
    padding: 1rem;
    background-color: #f8fafd;
    border-radius: 8px;
  }

  .user-info-item {
    margin-bottom: 0.5rem;
    color: #2c3e50;
  }

  .body-part-section {
    margin-bottom: 2rem;
    border: 1px solid #e9ecef;
    border-radius: 8px;
    padding: 1.5rem;
  }

  .body-part-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 1rem;
    padding-bottom: 0.5rem;
    border-bottom: 2px solid #e9ecef;
  }

  .body-part-title {
    color: #2c3e50;
    font-size: 1.4rem;
    font-weight: 600;
    margin: 0;
  }

  .menu-content {
    white-space: pre-line;
    color: #2c3e50;
    line-height: 1.6;
  }

  .training-history {
    margin-top: 1rem;
    padding-top: 1rem;
    border-top: 1px solid #e9ecef;
  }

  .history-title {
    font-size: 1.1rem;
    color: #2c3e50;
    margin-bottom: 0.5rem;
  }

  .history-list {
    max-height: 200px;
    overflow-y: auto;
    background-color: #f8fafd;
    border-radius: 6px;
    padding: 0.5rem;
  }

  .history-item {
    padding: 0.8rem;
    border-bottom: 1px solid #e9ecef;
    font-size: 0.9rem;
  }

  .history-date {
    color: #6c757d;
    font-size: 0.8rem;
  }

    .history-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 0.5rem;
  }

  .history-delete-btn {
    padding: 0.2rem 0.5rem;
    background-color: #e74c3c;
    color: white;
    border-radius: 4px;
    font-size: 0.8rem;
    text-decoration: none;
    transition: background-color 0.3s ease;
  }

  .history-delete-btn:hover {
    background-color: #c0392b;
    text-decoration: none;
    color: white;
  }

  .history-content {
    padding-left: 0.5rem;
    border-left: 2px solid #e9ecef;
  }

  .btn {
    padding: 0.5rem 1rem;
    border-radius: 5px;
    transition: all 0.3s ease;
    cursor: pointer;
  }

  .btn-edit {
    background-color: #2ecc71;
    border-color: #27ae60;
    color: white;
  }

  .btn-edit:hover {
    background-color: #27ae60;
  }

  .btn-record {
    background-color: #3498db;
    border-color: #2980b9;
    color: white;
  }

  .btn-record:hover {
    background-color: #2980b9;
  }

  .modal {
    display: none;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.5);
  }

  .modal-content {
    position: relative;
    background-color: white;
    margin: 10% auto;
    padding: 2rem;
    max-width: 500px;
    border-radius: 8px;
  }

  .modal-close {
    position: absolute;
    top: 1rem;
    right: 1rem;
    cursor: pointer;
  }

  .form-group {
    margin-bottom: 1rem;
  }

  .form-label {
    display: block;
    margin-bottom: 0.5rem;
    color: #2c3e50;
  }

  .form-input {
    width: 100%;
    padding: 0.5rem;
    border: 1px solid #e9ecef;
    border-radius: 4px;
  }

  @media (max-width: 768px) {
    .content-wrapper {
      padding: 1rem;
    }

    .modal-content {
      margin: 5% 1rem;
    }
  }
</style>
<div class="workout-container">
  <div class="container">
    <div class="content-wrapper">
      <h1 class="page-title">トレーニングメニュー</h1>

      <div class="user-info">
        <div class="user-info-item">
          <strong>名前:</strong> <%= @user.name %>
        </div>
        
      </div>

      <% parts = { 
        chest: "胸部（Chest）", 
        back: "背中（Back）", 
        shoulder: "肩（Shoulder）",
        arms: "腕（Arms）", 
        abs: "腹筋（Abs）", 
        thighs: "太もも（Thighs）"
      } %>

      <% parts.each do |part, title| %>
        <section class="body-part-section" id="<%= part %>-section">
          <div class="body-part-header">
            <h2 class="body-part-title"><%= title %></h2>
            
          </div>

          <div class="menu-content">
            <% if @user.send(part).present? %>
              <%= @user.send(part) %>
            <% else %>
              <p class="empty-menu">メニューが未設定です</p>
            <% end %>
          </div>
        </section>
      <% end %>
    </div>
  </div>
</div>